---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    toolkit.fluxcd.io/tenant: platform
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  url: https://charts.external-secrets.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 5m0s
  chart: external-secrets
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: external-secrets
  version: "0.*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: external-secrets
      version: "0.*"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 5m
  values:
    installCRDs: true
