apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/metrics-server
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m0s
  chart: metrics-server
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: metrics-server
  version: "3.*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: metrics-server
      version: "3.*"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      interval: 5m
