---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    toolkit.fluxcd.io/tenant: platform
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m0s
  chart: cert-manager
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: cert-manager
  version: "1.*"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      version: "1.*"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 5m
  values:
    installCRDs: true
